CREATE TABLE IF NOT EXISTS User  (
	userID TEXT PRIMARY KEY NOT NULL UNIQUE,
	email TEXT NOT NULL UNIQUE,
	name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Project (
    projectID TEXT PRIMARY KEY NOT NULL UNIQUE,
    userID TEXT NOT NULL,
    name TEXT NOT NULL,
    createdAt TEXT NOT NULL,
	FOREIGN KEY(userID) REFERENCES User(userID)
);

CREATE TABLE IF NOT EXISTS Page (
	pageID TEXT PRIMARY KEY NOT NULL UNIQUE,
	projectID TEXT NOT NULL,
	title TEXT NOT NULL,
	url TEXT NOT NULL,
	language TEXT NOT NULL,
	tokens INTEGER,
	FOREIGN KEY(projectID) REFERENCES Project(projectID)
);

CREATE TABLE IF NOT EXISTS PageStatus (
	pageID TEXT PRIMARY KEY NOT NULL UNIQUE,
	status TEXT NOT NULL,
	FOREIGN KEY(pageID) REFERENCES Page(pageID)
);

CREATE TABLE IF NOT EXISTS Auth {
	userID TEXT PRIMARY KEY NOT NULL UNIQUE,
	password TEXT NOT NULL,
	FOREIGN KEY(userID) REFERENCES User(userID)
}
