[package]
name = "web_scout"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
crc32fast = "1.3.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.91"
serde_yaml = "0.9.16"



