name = "webscout"
main = "worker/index.ts"
compatibility_date = "2023-03-02"
kv_namespaces = [
    { binding = "KV_LANG", id = "dcde05f76a94414dac8f55428fe7a7fb", preview_id = "09d49fae68c34a60af3254c4e9bbc535" }
]
[[r2_buckets]]
binding= "LANG_PACKS"
bucket_name = 'langpacks'
preview_bucket_name = 'previewlangpacks'
