name = "webscout"
main = "build/worker/shim.mjs"
compatibility_date = "2022-01-20"

kv_namespaces = [
  { binding = "LANG-PACKS", id = "LPACKS" }
]


[vars]
WORKERS_RS_VERSION = "0.0.9"

[build]
command = "cargo install -q worker-build --version 0.0.7 && worker-build --release"
