use crate::utils::text_to_hashset;
use alloc::string::String;
use hashbrown::HashSet;
use lazy_static::lazy_static;
mod arabic;
mod danish;
mod dutch;
mod english;
mod finnish;
mod french;
mod german;
mod greek;
mod hungarian;
mod italian;
mod portuguese;
mod romanian;
mod russian;
mod spanish;
mod swedish;
mod turkish;
lazy_static! {
    pub static ref ARABIC: HashSet<String> = text_to_hashset(arabic::AR_STOPWORDS);
    pub static ref DANISH: HashSet<String> = text_to_hashset(danish::DA_STOPWORDS);
    pub static ref DUTCH: HashSet<String> = text_to_hashset(dutch::NL_STOPWORDS);
    pub static ref ENGLISH: HashSet<String> = text_to_hashset(english::EN_STOPWORDS);
    pub static ref FINNISH: HashSet<String> = text_to_hashset(finnish::FI_STOPWORDS);
    pub static ref FRENCH: HashSet<String> = text_to_hashset(french::FR_STOPWORDS);
    pub static ref GERMAN: HashSet<String> = text_to_hashset(german::DE_STOPWORDS);
    pub static ref GREEK: HashSet<String> = text_to_hashset(greek::EL_STOPWORDS);
    pub static ref HUNGARIAN: HashSet<String> = text_to_hashset(hungarian::HU_STOPWORDS);
    pub static ref ITALIAN: HashSet<String> = text_to_hashset(italian::IT_STOPWORDS);
    pub static ref PORTUGUESE: HashSet<String> = text_to_hashset(portuguese::PT_STOPWORDS);
    pub static ref ROMANIAN: HashSet<String> = text_to_hashset(romanian::RO_STOPWORDS);
    pub static ref RUSSIAN: HashSet<String> = text_to_hashset(russian::RU_STOPWORDS);
    pub static ref SPANISH: HashSet<String> = text_to_hashset(spanish::ES_STOPWORDS);
    pub static ref SWEDISH: HashSet<String> = text_to_hashset(swedish::SV_STOPWORDS);
    pub static ref TURKISH: HashSet<String> = text_to_hashset(turkish::TR_STOPWORDS);
}
